version: "3.8"
services:
  app:
    build:
      args:
        user: mahdi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: cms
    container_name: cms-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cms-network

  nginx:
    image: nginx:alpine
    container_name: cms-nginx
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./:/var/www
      # - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cms-network
networks:
  cms-network:
    driver: bridge
